In [2]:
import numpy as np

In [3]:
# Collect Data
x = np.array([[0, 0, 1],
              [0, 1, 1],
              [1, 0, 1],
              [1, 1, 1]])

y = np.array([[0],
             [1],
             [1],
             [0]])

In [4]:
print(x)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


In [5]:
print(y)

[[0]
 [1]
 [1]
 [0]]


 * using the [random number generator](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.random.html) from numpy below. Very interesting [notation](http://stackoverflow.com/questions/4396290/what-does-this-square-bracket-and-parenthesis-bracket-notation-mean-first1-last) being used in the documentation. 

* notice the '- 1' ...this becomes the lower limit. 

In [6]:
# build model

num_epochs = 100000

#initialize weights
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

In [7]:
print(syn0)

[[-0.1730881   0.05353646  0.17231092  0.81429679]
 [ 0.75131126  0.15512077  0.52690436 -0.09837955]
 [ 0.76591374 -0.36945645 -0.40927908  0.16991113]]


In [8]:
print(syn1)

[[ 0.73824214]
 [ 0.90982015]
 [-0.16987628]
 [ 0.46158218]]


In [9]:
def nonlin(x, deriv = False):
    if(deriv == True):
        return x*(1-x)
    
    return 1/(1+np.exp(-x))
    

This uses the "transpose" of a matrix using numpy's matrix.T function. The documentation for the function is [here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.T.html) and the explanation for what a matrix transpose is, is [here](https://youtu.be/2t0003_sxtU?t=1m35s)

In [10]:
# Step 3: Train Model

for i in range(num_epochs):
    # feed forward through layers 0, 1, and 2
    layer0 = x
    layer1 = nonlin(np.dot(layer0, syn0))
    layer2 = nonlin(np.dot(layer1, syn1))
    
    # how inaccurate is our prediction? error known as 'cost'
    layer2_error = y - layer2
    
    if (i % 10000) == 0:
        print("Error" + str(np.mean(np.abs(layer2_error))))
    
    # int what direction is the target value (learned by calculus)
    layer2_delta = layer2_error * nonlin(layer2, deriv=True)
    
    # how much did each layer1 value contribute to layer2 error? T returns the transpose of the matrix
    layer1_error = layer2_delta.dot(syn1.T) 
    
    layer1_delta = layer1_error * nonlin(layer1, deriv=True)
    
    syn1 += layer1.T.dot(layer2_delta)
    syn0 += layer0.T.dot(layer1_delta)
    
    

Error0.500325656214
Error0.0107786578002
Error0.0072923409532
Error0.00585636144232
Error0.00502554551694
Error0.00446817691375
Error0.00406138049402
Error0.00374779535219
Error0.00349659697284
Error0.00328955715027
(3, 4)


## Below lie more introductory tidbits from the course module

In [30]:
scalar = np.array(3)

print(s.shape)
print(s)

z = s + 3

print(z)


vector = np.array([5, 4, 1])

print(vector)
print(vector.shape)

matrix = np.array([[4, 5, 6],
                   [7, 8, 9]])

print(matrix.shape)


tensor = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],
              [[[7],[8]],[[9],[10]],[[11],[12]]],
              [[[13],[14]],[[15],[16]],[[17],[17]]]
             ])

print(tensor.shape)
print(tensor)

values = [1,2,3,4,5]
values = np.array(values) + 5

print(values)

values += 5

print(values)

values *= 0

print(tensor.T)
print(matrix.T)

()
3
6
[5 4 1]
(3,)
(2, 3)
(3, 3, 2, 1)
[[[[ 1]
   [ 2]]

  [[ 3]
   [ 4]]

  [[ 5]
   [ 6]]]


 [[[ 7]
   [ 8]]

  [[ 9]
   [10]]

  [[11]
   [12]]]


 [[[13]
   [14]]

  [[15]
   [16]]

  [[17]
   [17]]]]
[ 6  7  8  9 10]
[11 12 13 14 15]
[[[[ 1  7 13]
   [ 3  9 15]
   [ 5 11 17]]

  [[ 2  8 14]
   [ 4 10 16]
   [ 6 12 17]]]]
[[4 7]
 [5 8]
 [6 9]]
